[package]
name = "rstankgame"
version = "0.0.1"
edition = "2021"

[dependencies]
as-any = "0.3.1"
lazy_static = "1.5.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
typetag = "0.2.18"
